name: Acciojob Tests
on:
 push:
    branches: [ "main","master" ]

jobs:
  calling-acciojob-main-action:
    uses: acciojob/acciojob-tests-action/.github/workflows/main-action.yml@main
    with:
        node-version: '14.x' # or '16.x'
    secrets: inherit
